name: Run Specs On macOS
on: [push, pull_request]

jobs:
  cross_compile_windows_obj:
    name: Build Crystal on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set env
        run: |
          echo ::set-env name=CURRENT_TAG::$(echo ${GITHUB_REF:10})
          echo ::set-env name=PATH::"/usr/local/opt/llvm/bin:$PATH"
          echo ::set-env name=TRAVIS_OS_NAME::"osx"
      - name: Prepare system
        run: |          
          bin/ci prepare_system
          echo ::set-env name=PKG_CONFIG_PATH::"$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig"
      - name: Build
        run: |          
          bin/ci prepare_build
          bin/ci build
